// server/models/WagePolicy.js
const mongoose = require("mongoose");

const wagePolicySchema = new mongoose.Schema(
  {
    year: { type: Number, required: true },
    minWage: { type: Number, required: true },
    weeklyHours: { type: Number, default: 40 },
    appliedFrom: { type: Date, required: true },
    appliedUntil: { type: Date },
    autoGenerated: { type: Boolean, default: false },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    memo: { type: String },
  },
  { timestamps: true }
);

wagePolicySchema.index({ year: 1 }, { unique: true });

module.exports = mongoose.model("WagePolicy", wagePolicySchema);
