// added by new ERP update
export const MENUS = {
  OPEN_START: "openStart",
  WASTE_MOVE: "wasteMove",
  ENTRANCE: "entrance",
  SETTLEMENT: "settlement",
  SALES: "sales",
  DAYBOOK: "daybook",
  INVENTORY: "inventoryTemplate",
  TEMPLATE: "inventoryLibrary",
} as const;

export const FEATURE_PERMISSIONS = {
  OPEN_SHIFT: "OPEN_SHIFT",
  CLOSE_SALE: "CLOSE_SALE",
  SALES_INPUT: "SALES_INPUT",
  INVENTORY_BASIC: "INVENTORY_BASIC",
  WASTE_INPUT: "WASTE_INPUT",
  EQUIPMENT_INPUT: "EQUIPMENT_INPUT",
  ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
  PERMISSION_MANAGE: "PERMISSION_MANAGE",
  APPROVAL_MANAGE: "APPROVAL_MANAGE",
  LOG_VIEW: "LOG_VIEW",
  ADMIN_PANEL_ACCESS: "ADMIN_PANEL_ACCESS",
} as const;

export type FeaturePermissionKey = (typeof FEATURE_PERMISSIONS)[keyof typeof FEATURE_PERMISSIONS];

export const EMPLOYEE_FEATURES: FeaturePermissionKey[] = [
  FEATURE_PERMISSIONS.OPEN_SHIFT,
  FEATURE_PERMISSIONS.CLOSE_SALE,
  FEATURE_PERMISSIONS.SALES_INPUT,
  FEATURE_PERMISSIONS.INVENTORY_BASIC,
  FEATURE_PERMISSIONS.WASTE_INPUT,
  FEATURE_PERMISSIONS.EQUIPMENT_INPUT,
];

export const ADMIN_FEATURES: FeaturePermissionKey[] = [
  ...EMPLOYEE_FEATURES,
  FEATURE_PERMISSIONS.ADMIN_DASHBOARD,
  FEATURE_PERMISSIONS.PERMISSION_MANAGE,
  FEATURE_PERMISSIONS.APPROVAL_MANAGE,
  FEATURE_PERMISSIONS.LOG_VIEW,
  FEATURE_PERMISSIONS.ADMIN_PANEL_ACCESS,
];

export type MenuPermissionKey = (typeof MENUS)[keyof typeof MENUS];
